# This file contains values from Cookiecutter

default_context:
  project_name: "fluentqa-pdao"
  project_plug: "fluentqa_pdao"
  project_description: "Awesome `fluentqa_pdao` is a Python cli/package "
  organization: "fluent-qa"
  minimal_python_version: 3.10
  github_name: "fluent-qa"
  email: "hello@fluent-qa.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "simple"
